package com.saaspaymentsolutions.axion;

import android.content.Context;
import android.content.SharedPreferences;

import com.saaspaymentsolutions.axion.port.VoidPortSettings;

import org.json.JSONArray;
import org.json.JSONObject;

import java.util.HashMap;
import java.util.Map;
import java.util.Set;

/**
 * SharedPreferences wrapper for the AI settings file ({@code ia_settings}) that
 * transparently encrypts secrets (provider API keys, MCP server headers) with
 * {@link SecretStore} before they reach disk, and decrypts them on read.
 *
 * Migration: on first access, legacy plaintext values are re-written encrypted
 * by {@link #migrateSecrets}, so existing installs upgrade silently.
 *
 * All other methods delegate untouched — this wrapper only rewrites the values
 * that match {@link SecretKeys#matches(String)}.
 */
public final class SecurePrefs implements SharedPreferences {

    /** Preference keys whose values are secrets and must be encrypted at rest. */
    public static final class SecretKeys {
        private SecretKeys() {
        }

        /** GitHub Personal Access Token stored in the AI settings file. */
        private static boolean isGithubToken(String key) {
            return "github_token".equals(key);
        }

        /** Matches the per-provider keys generated by VoidPortSettings.providerPrefKey. */
        public static boolean matches(String key) {
            if (key == null) {
                return false;
            }
            return isGithubToken(key)
                    || (key.startsWith("provider_config_")
                        && (key.endsWith("_api_key") || key.endsWith("_headers")));
        }

        public static boolean matchesMcp(String key) {
            return "mcp_config".equals(key);
        }
    }

    private final SharedPreferences delegate;

    private SecurePrefs(SharedPreferences delegate) {
        this.delegate = delegate;
    }

    /** Returns the hardened view of the AI settings file. */
    public static SharedPreferences of(Context context) {
        return new SecurePrefs(
                context.getApplicationContext()
                        .getSharedPreferences(VoidPortSettings.PREFS_NAME, Context.MODE_PRIVATE));
    }

    /** Re-encrypts legacy plaintext secrets found in the file; idempotent. */
    public static void migrateSecrets(SharedPreferences prefs) {
        try {
            Map<String, ?> all = prefs.getAll();
            boolean changed = false;
            SharedPreferences.Editor realEditor = prefs.edit();
            for (Map.Entry<String, ?> entry : all.entrySet()) {
                String key = entry.getKey();
                Object value = entry.getValue();
                if (!(value instanceof String)) {
                    continue;
                }
                String raw = (String) value;
                if (SecretKeys.matches(key) || SecretKeys.matchesMcp(key)) {
                    String upgraded = encryptValue(key, raw);
                    if (!upgraded.equals(raw)) {
                        realEditor.putString(key, upgraded);
                        changed = true;
                    }
                }
            }
            if (changed) {
                realEditor.apply();
            }
        } catch (Exception ignored) {
            // Migration is best-effort; runtime read/write paths also encrypt.
        }
    }

    private static String encryptValue(String key, String raw) {
        if (raw == null || raw.isEmpty() || SecretStore.isEncrypted(raw)) {
            return raw;
        }
        if (SecretKeys.matchesMcp(key)) {
            return encryptMcpConfig(raw);
        }
        return SecretStore.encrypt(raw);
    }

    private static String decryptValue(String key, String raw) {
        if (raw == null || raw.isEmpty()) {
            return raw;
        }
        if (SecretKeys.matchesMcp(key)) {
            return decryptMcpConfig(raw);
        }
        return SecretStore.decrypt(raw);
    }

    /**
     * The MCP config JSON holds one object per server; only per-server header
     * objects are secret, so encryption is applied field-wise to keep the rest
     * of the config inspectable.
     */
    private static String encryptMcpConfig(String rawJson) {
        try {
            JSONObject root = new JSONObject(rawJson);
            JSONObject servers = root.optJSONObject("mcpServers");
            boolean changed = false;
            if (servers != null) {
                JSONArray names = servers.names();
                for (int i = 0; names != null && i < names.length(); i++) {
                    String name = names.optString(i, "");
                    JSONObject server = servers.optJSONObject(name);
                    JSONObject headers = server == null ? null : server.optJSONObject("headers");
                    if (headers != null && headers.length() > 0 && !SecretStore.isEncrypted(headers.toString())) {
                        server.put("headers", SecretStore.encrypt(headers.toString()));
                        changed = true;
                    }
                }
            }
            return changed ? root.toString() : rawJson;
        } catch (Exception e) {
            return SecretStore.encrypt(rawJson);
        }
    }

    private static String decryptMcpConfig(String rawJson) {
        try {
            JSONObject root = new JSONObject(rawJson);
            JSONObject servers = root.optJSONObject("mcpServers");
            boolean changed = false;
            if (servers != null) {
                JSONArray names = servers.names();
                for (int i = 0; names != null && i < names.length(); i++) {
                    String name = names.optString(i, "");
                    JSONObject server = servers.optJSONObject(name);
                    String headers = server == null ? null : server.optString("headers", "");
                    if (headers != null && SecretStore.isEncrypted(headers)) {
                        String plain = SecretStore.decrypt(headers);
                        server.put("headers", plain.isEmpty() ? new JSONObject() : new JSONObject(plain));
                        changed = true;
                    }
                }
            }
            return changed ? root.toString() : rawJson;
        } catch (Exception e) {
            return SecretStore.decrypt(rawJson);
        }
    }

    // ---- SharedPreferences delegation with secret transform ----

    @Override
    public String getString(String key, String defValue) {
        String value = delegate.getString(key, defValue);
        if (value == null || value.equals(defValue)) {
            return value;
        }
        return decryptValue(key, value);
    }

    @Override
    public Editor edit() {
        return new SecureEditor(delegate.edit());
    }

    @Override
    public boolean contains(String key) {
        return delegate.contains(key);
    }

    @Override
    public Map<String, ?> getAll() {
        Map<String, ?> raw = delegate.getAll();
        Map<String, Object> all = new HashMap<>(raw);
        // Decrypt secret entries for callers that scan the whole file.
        for (String key : all.keySet().toArray(new String[0])) {
            Object value = all.get(key);
            if (value instanceof String && (SecretKeys.matches(key) || SecretKeys.matchesMcp(key))) {
                all.put(key, decryptValue(key, (String) value));
            }
        }
        return all;
    }

    @Override
    public void registerOnSharedPreferenceChangeListener(OnSharedPreferenceChangeListener listener) {
        delegate.registerOnSharedPreferenceChangeListener(listener);
    }

    @Override
    public void unregisterOnSharedPreferenceChangeListener(OnSharedPreferenceChangeListener listener) {
        delegate.unregisterOnSharedPreferenceChangeListener(listener);
    }

    // Not used by this app's settings flows; kept for interface completeness.
    @Override
    public Set<String> getStringSet(String key, Set<String> defValues) {
        return delegate.getStringSet(key, defValues);
    }

    @Override
    public int getInt(String key, int defValue) {
        return delegate.getInt(key, defValue);
    }

    @Override
    public long getLong(String key, long defValue) {
        return delegate.getLong(key, defValue);
    }

    @Override
    public float getFloat(String key, float defValue) {
        return delegate.getFloat(key, defValue);
    }

    @Override
    public boolean getBoolean(String key, boolean defValue) {
        return delegate.getBoolean(key, defValue);
    }

    /** Editor that encrypts secret keys before persisting. */
    private static final class SecureEditor implements Editor {
        private final Editor delegate;

        SecureEditor(Editor delegate) {
            this.delegate = delegate;
        }

        @Override
        public Editor putString(String key, String value) {
            if (SecretKeys.matches(key) || SecretKeys.matchesMcp(key)) {
                delegate.putString(key, encryptValue(key, value));
            } else {
                delegate.putString(key, value);
            }
            return this;
        }

        @Override
        public Editor putStringSet(String key, Set<String> values) {
            delegate.putStringSet(key, values);
            return this;
        }

        @Override
        public Editor putInt(String key, int value) {
            delegate.putInt(key, value);
            return this;
        }

        @Override
        public Editor putLong(String key, long value) {
            delegate.putLong(key, value);
            return this;
        }

        @Override
        public Editor putFloat(String key, float value) {
            delegate.putFloat(key, value);
            return this;
        }

        @Override
        public Editor putBoolean(String key, boolean value) {
            delegate.putBoolean(key, value);
            return this;
        }

        @Override
        public Editor remove(String key) {
            delegate.remove(key);
            return this;
        }

        @Override
        public Editor clear() {
            delegate.clear();
            return this;
        }

        @Override
        public boolean commit() {
            return delegate.commit();
        }

        @Override
        public void apply() {
            delegate.apply();
        }
    }
}
